# Render Deployment Configuration
# Deploy to Render with: render.yaml

services:
  # PostgreSQL Database
  - type: pserv
    name: sms-postgres
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./infra/Dockerfile.postgres
    envVars:
      - key: POSTGRES_DB
        value: school_management
      - key: TZ
        value: Africa/Monrovia

  # Redis
  - type: redis
    name: sms-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: noeviction

  # API Service
  - type: web
    name: sms-api
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./infra/Dockerfile.api
    healthCheckPath: /health
    envVars:
      - key: TZ
        value: Africa/Monrovia
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sms-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: sms-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SEED_ADMIN_EMAIL
        value: admin@school.local
      - key: SEED_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMS_PROVIDER
        value: log
      - key: DEFAULT_CURRENCY
        value: LRD

  # Worker Service
  - type: worker
    name: sms-worker
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./infra/Dockerfile.worker
    envVars:
      - key: TZ
        value: Africa/Monrovia
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: sms-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: sms-redis
          type: redis
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: SMS_PROVIDER
        value: log

  # Web Frontend
  - type: web
    name: sms-web
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./infra/Dockerfile.web
    envVars:
      - key: TZ
        value: Africa/Monrovia
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: sms-api
          type: web
          property: host

databases:
  - name: sms-postgres
    databaseName: school_management
    region: oregon
    plan: starter
